[2024-11-04T16:38:50.193+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T16:38:48.446267+00:00 [queued]>
[2024-11-04T16:38:50.211+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T16:38:48.446267+00:00 [queued]>
[2024-11-04T16:38:50.215+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T16:38:50.257+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): steam_load> on 2024-11-04 16:38:48.446267+00:00
[2024-11-04T16:38:50.269+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2024-11-04T16:38:50.272+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_game_pipeline', 'steam_load', 'manual__2024-11-04T16:38:48.446267+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/steam_dag.py', '--cfg-path', '/tmp/tmpi18hh209']
[2024-11-04T16:38:50.276+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask steam_load
[2024-11-04T16:38:50.359+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T16:38:48.446267+00:00 [running]> on host f6d6761c5673
[2024-11-04T16:38:50.669+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jordan Welborn' AIRFLOW_CTX_DAG_ID='etl_game_pipeline' AIRFLOW_CTX_TASK_ID='steam_load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T16:38:48.446267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T16:38:48.446267+00:00'
[2024-11-04T16:38:50.670+0000] {logging_mixin.py:151} INFO - Current Working Directory: /opt/airflow
[2024-11-04T16:38:51.208+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/game_pipeline.py", line 60, in load_data
    load_data_to_azure(games_df,game_path)
  File "/opt/airflow/etls/game_etl.py", line 151, in load_data_to_azure
    data.to_csv(AZURE_STORAGE + file_name, storage_options={
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 718, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 441, in _get_filepath_or_buffer
    raise ValueError(
ValueError: storage_options passed with file object or non-fsspec file path
[2024-11-04T16:38:51.233+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_game_pipeline, task_id=steam_load, execution_date=20241104T163848, start_date=20241104T163850, end_date=20241104T163851
[2024-11-04T16:38:51.244+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task steam_load (storage_options passed with file object or non-fsspec file path; 108)
[2024-11-04T16:38:51.286+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-04T16:38:51.300+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
