[2024-11-04T07:09:11.235+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_game_pipeline.game_extraction manual__2024-11-04T07:04:05.571353+00:00 [queued]>
[2024-11-04T07:09:11.245+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_game_pipeline.game_extraction manual__2024-11-04T07:04:05.571353+00:00 [queued]>
[2024-11-04T07:09:11.245+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-11-04T07:09:11.257+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): game_extraction> on 2024-11-04 07:04:05.571353+00:00
[2024-11-04T07:09:11.261+0000] {standard_task_runner.py:57} INFO - Started process 63 to run task
[2024-11-04T07:09:11.264+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_game_pipeline', 'game_extraction', 'manual__2024-11-04T07:04:05.571353+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/steam_dag.py', '--cfg-path', '/tmp/tmp3a9xo6gq']
[2024-11-04T07:09:11.268+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask game_extraction
[2024-11-04T07:09:11.313+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_game_pipeline.game_extraction manual__2024-11-04T07:04:05.571353+00:00 [running]> on host 09304c0ebd50
[2024-11-04T07:09:11.506+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jordan Welborn' AIRFLOW_CTX_DAG_ID='etl_game_pipeline' AIRFLOW_CTX_TASK_ID='game_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T07:04:05.571353+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T07:04:05.571353+00:00'
[2024-11-04T07:09:11.507+0000] {logging_mixin.py:151} INFO - Extracting and transforming game data...
[2024-11-04T07:09:11.939+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/game_pipeline.py", line 19, in extract_data
    games = extract_all_games()
  File "/opt/airflow/etls/game_etl.py", line 59, in extract_all_games
    token = get_igdb_token()
  File "/opt/airflow/etls/game_etl.py", line 26, in get_igdb_token
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?grant_type=client_credentials
[2024-11-04T07:09:11.952+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_game_pipeline, task_id=game_extraction, execution_date=20241104T070405, start_date=20241104T070911, end_date=20241104T070911
[2024-11-04T07:09:11.963+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task game_extraction (400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?grant_type=client_credentials; 63)
[2024-11-04T07:09:11.998+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-04T07:09:12.010+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
