[2024-11-04T07:09:10.457+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T07:04:05.571353+00:00 [queued]>
[2024-11-04T07:09:10.464+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T07:04:05.571353+00:00 [queued]>
[2024-11-04T07:09:10.464+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-11-04T07:09:10.476+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): steam_load> on 2024-11-04 07:04:05.571353+00:00
[2024-11-04T07:09:10.480+0000] {standard_task_runner.py:57} INFO - Started process 60 to run task
[2024-11-04T07:09:10.482+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_game_pipeline', 'steam_load', 'manual__2024-11-04T07:04:05.571353+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/steam_dag.py', '--cfg-path', '/tmp/tmpk7c8_m59']
[2024-11-04T07:09:10.485+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask steam_load
[2024-11-04T07:09:10.525+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_game_pipeline.steam_load manual__2024-11-04T07:04:05.571353+00:00 [running]> on host 09304c0ebd50
[2024-11-04T07:09:10.727+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jordan Welborn' AIRFLOW_CTX_DAG_ID='etl_game_pipeline' AIRFLOW_CTX_TASK_ID='steam_load' AIRFLOW_CTX_EXECUTION_DATE='2024-11-04T07:04:05.571353+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-04T07:04:05.571353+00:00'
[2024-11-04T07:09:10.730+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/game_pipeline.py", line 52, in load_data
    games_df = pd.read_csv(game_path)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/data/GameData.csv'
[2024-11-04T07:09:10.741+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_game_pipeline, task_id=steam_load, execution_date=20241104T070405, start_date=20241104T070910, end_date=20241104T070910
[2024-11-04T07:09:10.753+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task steam_load ([Errno 2] No such file or directory: '/data/GameData.csv'; 60)
[2024-11-04T07:09:10.774+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-04T07:09:10.792+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
